#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend donp.tech
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        servr 296954-web-01 3.85.16.215:80
        server 296954-web-02 18.233.67.195:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
